apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-update-merge-fallback

configMapGenerator:
  - name: test-envfrom
    literals:
      - "env=KEY1=VALUE1\nKEY2=VALUE2\n"

resources:
- namespace.yaml
- ../../_example_app

patches:
  - path: patch_deployment_envfrom.yaml
