apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: invalid
  # invalid namespace scoped but no namespace
subjects:
- kind: Group
  name: admins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
