apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test-update-recreate-roleref
  name: test-initial
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test
  namespace: test-update-recreate-roleref
subjects:
- kind: ServiceAccount
  name: default
  namespace: test-update-recreate-roleref
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: test-initial
  apiGroup: rbac.authorization.k8s.io
