apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-update-recreate-name-or-namespace-change

resources:
- namespace.yaml

configMapGenerator:
- name: test
  options:
    disableNameSuffixHash: true
