name: Acceptance Tests

on: push

jobs:
  tf_acc_tests:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1

    - name: 'Setup Kind'
      uses: engineerd/setup-kind@v0.1.0
      with:
        version: "v0.6.1"

    - name: 'Setup Go'
      uses: actions/setup-go@v1
      with:
        go-version: "1.13.5"

    - name: 'Run tests'
      run: |
        export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
        go test -v
      env:
        TF_ACC: '1'
